#!/usr/bin/env python3
"""Generate portfolio Markdown from data/projects.yaml."""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "data" / "projects.yaml"
GENERATED = ROOT / "docs" / "_generated"
PROJECTS_DIR = ROOT / "docs" / "projects"

HEADER = "<!-- Generated by scripts/generate_portfolio.py — do not edit by hand -->\n"


def load_projects() -> list[dict]:
    with REGISTRY.open(encoding="utf-8") as fh:
        data = yaml.safe_load(fh)
    return data["projects"]


def link_button(label: str, url: str | None, *, primary: bool = False) -> str:
    if not url:
        return ""
    if primary:
        return f"[{label}]({url}){{ .md-button .md-button--primary }}"
    return f"[{label}]({url}){{ .md-button }}"


def project_card(project: dict) -> str:
    lines = [
        '<div class="project-card" markdown="1">',
        f"### {project['name']}",
        "",
        project["summary"],
        "",
    ]
    meta = []
    if project.get("language"):
        meta.append(f"**Stack:** {project['language']}")
    meta.append(f"**Status:** {project['status']}")
    if meta:
        lines.append(" · ".join(meta))
        lines.append("")

    actions = []
    for label, key, primary in (
        ("Docs", "docs", True),
        ("Repo", "repo", False),
        ("Demo", "demo", False),
    ):
        btn = link_button(label, project.get(key), primary=primary)
        if btn:
            actions.append(btn)
    if actions:
        lines.append(" ".join(actions))
        lines.append("")

    lines.append("</div>")
    return "\n".join(lines)


def cards_grid(projects: list[dict]) -> str:
    if not projects:
        return "_No projects in this section._\n"
    parts = ['<div class="project-card-grid" markdown="1">', ""]
    for p in projects:
        parts.append(project_card(p))
        parts.append("")
    parts.append("</div>")
    return "\n".join(parts)


def write_current_work(projects: list[dict]) -> None:
    current = [p for p in projects if p.get("current")]
    current.sort(key=lambda p: (not p.get("featured"), p["name"].lower()))
    body = HEADER + cards_grid(current)
    (GENERATED / "home-current-work.md").write_text(body, encoding="utf-8")


def section(title: str, intro: str, projects: list[dict]) -> str:
    lines = [f"## {title}", "", intro, ""]
    if projects:
        lines.append(cards_grid(projects))
    else:
        lines.append("_None listed._")
    lines.append("")
    return "\n".join(lines)


def write_projects_index(projects: list[dict]) -> None:
    featured = [p for p in projects if p.get("featured")]
    active = [p for p in projects if p.get("status") == "active" and not p.get("featured")]
    maintained = [p for p in projects if p.get("status") == "maintained"]
    experimental = [p for p in projects if p.get("status") == "experimental"]
    historical = [p for p in projects if p.get("status") in {"historical", "archived"}]

    intro = """# Projects

Portfolio of independent software, documentation sites, and experiments. Entries are
generated from [`data/projects.yaml`](https://github.com/sempervent/sempervent.github.io/blob/main/data/projects.yaml)
so descriptions stay in one reviewable place.

**Status legend:** *active* — ongoing focus; *maintained* — usable with occasional updates;
*experimental* — lab/prototype; *historical* — kept for reference.

See also **[Project documentation sites](documentation-sites.md)** for verified GitHub Pages deployments.
"""
    parts = [HEADER, intro, ""]
    parts.append(
        section(
            "Featured",
            "Flagship or especially representative work.",
            sorted(featured, key=lambda p: p["name"].lower()),
        )
    )
    parts.append(
        section(
            "Active development",
            "Additional projects with recent independent development.",
            sorted(active, key=lambda p: p["name"].lower()),
        )
    )
    parts.append(
        section(
            "Maintained tools & platforms",
            "Libraries, portals, and utilities that remain useful.",
            sorted(maintained, key=lambda p: p["name"].lower()),
        )
    )
    parts.append(
        section(
            "Experiments & documentation",
            "Wikis, comparisons, games-in-progress, and strange machinery.",
            sorted(experimental, key=lambda p: p["name"].lower()),
        )
    )
    parts.append(
        section(
            "Historical archive",
            "Older web apps and prototypes — preserved, not promoted as current work.",
            sorted(historical, key=lambda p: p["name"].lower()),
        )
    )

    PROJECTS_DIR.mkdir(parents=True, exist_ok=True)
    (PROJECTS_DIR / "index.md").write_text("\n".join(parts), encoding="utf-8")


def write_lab(projects: list[dict]) -> None:
    lab = [
        p
        for p in projects
        if p.get("category") in {"creative", "games"}
        or p.get("status") == "experimental"
        and p.get("category") != "documentation"
    ]
    lab = sorted({p["slug"]: p for p in lab}.values(), key=lambda p: p["name"].lower())

    intro = """# Lab & Experiments

Unusual projects, games, generative systems, and homelab oddities. Material here is
**experimental** unless explicitly marked maintained — not production guidance.

For step-by-step creative tutorials, see **[Just for Fun](../tutorials/just-for-fun/index.md)**.
"""
    body = HEADER + intro + "\n" + cards_grid(lab)
    lab_dir = ROOT / "docs" / "lab"
    lab_dir.mkdir(parents=True, exist_ok=True)
    (lab_dir / "index.md").write_text(body, encoding="utf-8")


def write_documentation_sites(projects: list[dict]) -> None:
    verified_slugs = {
        "parqonaut",
        "dots",
        "music-rig",
        "blacklake-python",
        "s3-rust-data-portal",
        "gi",
        "wildfire-smoke-risk",
        "agent-llm-wiki-matrix",
        "postgres-query-autopsy",
        "smart-farm-wiki",
        "llm-wiki-template",
        "generative-midi-workbench",
        "opensampl",
    }
    with_docs = [
        p
        for p in projects
        if p.get("docs") and p.get("slug") in verified_slugs
    ]
    with_docs.sort(key=lambda p: p["name"].lower())

    lines = [
        HEADER,
        "# Project documentation sites",
        "",
        "Verified live documentation deployments (HTTP 200 as of the portfolio recon in",
        "`docs/maintainers/portfolio-recon-2026-09-30.md`). Repositories with GitHub Pages",
        "enabled but returning 404 are omitted until the deploy is fixed.",
        "",
        "| Project | Purpose | Site |",
        "| --- | --- | --- |",
    ]
    for p in with_docs:
        summary = p["summary"].replace("|", "\\|").replace("\n", " ")
        if len(summary) > 120:
            summary = summary[:117] + "..."
        lines.append(f"| {p['name']} | {summary} | [{p['docs']}]({p['docs']}) |")

    lines.append("")
    PROJECTS_DIR.mkdir(parents=True, exist_ok=True)
    (PROJECTS_DIR / "documentation-sites.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    sys.path.insert(0, str(ROOT / "scripts"))
    from validate_projects import validate_registry, load_registry  # noqa: WPS433

    try:
        data = load_registry()
    except (OSError, yaml.YAMLError, ValueError) as exc:
        print(f"Failed to load registry: {exc}", file=sys.stderr)
        return 1

    errors = validate_registry(data)
    if errors:
        for err in errors:
            print(err, file=sys.stderr)
        return 1

    projects = data["projects"]
    GENERATED.mkdir(parents=True, exist_ok=True)
    write_current_work(projects)
    write_projects_index(projects)
    write_lab(projects)
    write_documentation_sites(projects)
    print("Generated portfolio pages from data/projects.yaml")
    return 0


if __name__ == "__main__":
    sys.exit(main())
